### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by igor-petruk** [sergei-ivanov/maven-protoc-plugin#1]
It is better to explicitly to specify the license of any project. Github does not have a sort of default license. Just by publishing your project to github you accept some terms that allow to view and fork the project, but it is still uncertain.

**Comment by NersesAM** [comment]
Hi @sergei-ivanov, 

I would like to use this plugin in our project, but as there is no Licence we can't. Has anything changed in the last 3 years? 

Thanks,
Nerses

**Comment by sergei-ivanov** [comment]
I am sorry to disappoint you, but unfortunately nothing really changed in that time: I haven't got resources for a clean rewrite, Google people haven't shown a commitment to adopt the project, CodeHaus dev community was not interested in it either.

**Comment by saturnism** [comment]
hiya - quick ping wrt to license. ping me on twitter @saturnism and let's chat.

**Comment by sergei-ivanov** [comment]
Hello all,

We managed to amicably resolve licensing issues with Google. The plugin has been licensed under Apache 2.0 licence, and it has a new home now:
https://github.com/xolstice/protobuf-maven-plugin

This repository will be locked down shortly. Please submit issues and pull requests to the new repository.

Thank you for your patience.
Kind regards,

Sergei
