### ISSUE TITLE
URL specified in pluginRepository goes to 404 location

### ISSUE THREAD

**Issue by ssylvis** [sergei-ivanov/maven-protoc-plugin#23]
The URL listed in the README no longer works:

    <pluginRepositories>
        <pluginRepository>
            <id>protoc-plugin</id>
            <url>http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/</url>
        </pluginRepository>
    </pluginRepositories>

**Comment by sergei-ivanov** [comment]
This is because GitHub does not support directory listing. It does actually translate to the correct artefact download URLs if you specify it in a maven POM or in a repo manager config.
--
Sergei

**Comment by ssylvis** [comment]
Thanks Sergei.
I've included the <pluginRepositories> content in my project pom.xml and this is what I get on a fresh repo using "mvn clean install":
Downloading: http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is e1af12ca4cca29472f9c3df4f1238a75cc2f00ba for http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.pom

The 404 makes it so I cannot fetch a valid artifact.

**Comment by sergei-ivanov** [comment]
Hi,

Yes, indeed it seems to be a problem. We have always used it with a repo manager, and never ran into this issue.

It looks like in the effective POM the defaut 'central' repo for plugins is placed after the user-specified one. If you include maven central explicitly and place it before the protoc repo, it should work (I've just tested it locally):

```xml
<pluginRepositories>
    <pluginRepository>
        <id>central</id>
        <url>http://repo1.maven.org/maven2</url>
    </pluginRepository>
    <pluginRepository>
        <id>protoc-plugin</id>
        <url>http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/</url>
    </pluginRepository>
</pluginRepositories>
```

**Comment by ssylvis** [comment]
Ah, I see. That worked for me. Thanks Sergei!

**Comment by sergei-ivanov** [comment]
Hi,

I've also uploaded the artifacts to bintray, please see the latest README for instructions.

Sergei
