### ISSUE TITLE
Add support for custom native plugins

### ISSUE THREAD

**Issue by sergei-ivanov** [sergei-ivanov/maven-protoc-plugin#30]
Required parameters:
- ```plugin_id```: this can be automatically resolved by protoc to executable name (must be in the ```PATH```)

Optional:
- ```plugin_executable```: an explicit path to the executable
- ```output_directory```: to be derived by default from Maven project environment and ```plugin_id```
- ```parameter```: optional parameter to be passed to the plugin

All other parameters inherited from base mojos.
In order to avoid clashes with built-in plugins, need to check that ```plugin_id``` is not one of ```cpp```, ```java```, ```python``` or ```descriptor_set```.

Nice to have: support for toolchains. That will require two additional parameters: ```toolchain_type``` and ```toolchain_tool```.

**Comment by sergei-ivanov** [comment]
Upon request from ```grpc``` team, need to support resolution of protoc plugins as native artifacts from Maven repositories. Also need to support resolving ```protoc``` itself as a Maven artifact (there are plans to start deploying native ```protoc``` binaries for a range of platforms into Maven central).

**Comment by zhangkun83** [comment]
@sergei-ivanov thanks for adding this feature! In my [example project](https://github.com/zhangkun83/grpc-common/tree/use_exe_plugin_in_repo/java/java), ``mvn install`` doesn't seem to pull the plugin. I must have done something wrong. Could you take a look?

**Comment by sergei-ivanov** [comment]
@zhangkun83 Sorry, I saw your message on the grpc thread, but I have been away and did not have a chance to work on an integration test and documentation for the usage of native plugins as artifacts.
Your POM has a wrong parameter name, it should be `pluginArtifact`, not `protocPluginArtifact`. With the correct parameter everything works beautifully. I had to tweak the POM and the sources here and there to make the build portable (it broke in quite a few places on my test Windows machine because of the missing configuration) and sources compilable. Please take a look at the pull request.

**Comment by zhangkun83** [comment]
Thanks. It does work beautifully :)
