### ISSUE TITLE
Plugin location in README does not work

### ISSUE THREAD

**Issue by cristiklein** [sergei-ivanov/maven-protoc-plugin#31]
I tried downloading the plugin from the link given in the README:

http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/

But it does not work. Could you fix it?

Thanks,
Cristian

**Comment by sergei-ivanov** [comment]
Hello Cristian,

Please see #23
It is a known issue, but the files are actually there.

Kind regards,
Sergei

**Comment by sergei-ivanov** [comment]
Hi,

I've also uploaded the artifacts to bintray, please see the latest README for instructions.

Sergei

**Comment by cristiklein** [comment]
Cool. Thanks for letting me know!
