### ISSUE TITLE
Proto file source in android APK file

### ISSUE THREAD

**Issue by nikedlab** [sergei-ivanov/maven-protoc-plugin#32]
After as proto is compiled I found source proto file in generated classes folder, it lead that proto source code available in APK build file (I write for android). It is very insecure, I don't want to share my protocol to public. How I cant prevent it?

**Comment by sergei-ivanov** [comment]
Hi,

Currently, the source `.proto` definitions are attached to the build as resources (and eventually packaged into the final build artifact), and at the moment there is no control over this behaviour. We normally have a huge hierarchy of projects/libraries, and downstream projects may need to import or extend protos from the upstream projects. We are massively reliant on this feature. There is no way in Maven of defining a _transitive_ build-time dependency, which would only be required for build-time activities, but excluded from any packaging, such as `war`, `apk` or custom assemblies.

Your security concerns are absolutely valid, and I think the best I can do is to add a new mojo parameter to suppress the attachment of source `.proto` files as resources. As long as your downstream dependencies only use the generated message classes and do not need the `.proto`, you should be all right.

I shall look into implementing it shortly.

Kind regards,
Sergei

**Comment by sergei-ivanov** [comment]
Done. Will be part of the next release.
