### ISSUE TITLE
Configure .proto files path

### ISSUE THREAD

**Issue by 4ntoine** [sergei-ivanov/maven-protoc-plugin#37]
By default it's `src/main/proto` and it's ok for java. But for Android it should be changed (yes, now android studio supports `/src/main/java`-like paths but most current android project still use `/src` for java classes and `/proto` for .proto).

Can you add `protoPath` value to `configuration` section?

**Comment by sergei-ivanov** [comment]
It is already there:
http://sergei-ivanov.github.io/maven-protoc-plugin/compile-mojo.html#protoSourceRoot
Please confirm that it covers your needs and I'll close this ticket.

**Comment by 4ntoine** [comment]
works like a charm in android app:
```
<configuration>
    <!-- processes .proto files in /proto folder, generates .java -->
    <protoSourceRoot>${project.basedir}/proto</protoSourceRoot>
    <protocExecutable>protoc</protocExecutable>
    <checkStaleness>true</checkStaleness>
</configuration>
```

consider adding to the documentation or usage example (i was unable to find it). thanks.

**Comment by sergei-ivanov** [comment]
I am glad that it worked for you after the configuration adjustments. I am not developing for Android (or mobile in general), and as a result I have no idea if this configuration is IDE-specific or specific to Android builds. Apologies for my ignorance there. If you feel like it could benefit other people, a documentation pull request (either Usage or FAQ section) will be very welcome.
