### ISSUE TITLE
Does this plugin have the option to generate C# code as well?

### ISSUE THREAD

**Issue by jervin** [sergei-ivanov/maven-protoc-plugin#41]
I see in the usage page, python and C++.  It would be helpful to me if this plugin could also handle C#.

**Comment by jvstein** [comment]
New project is at: https://github.com/xolstice/protobuf-maven-plugin

**Comment by jervin** [comment]
Thank you will ask there..

**Comment by sergei-ivanov** [comment]
Thank you @jvstein. Unfortunately, there's no way to lock down the issues in this repo, save for disabling them in the settings (which effectively hides them completely from the view).
